# Matrix Operations and Linear Systems
## Progressive Lab: Matrix Operations, Linear Systems, and Independence 
### Overview 
This lab guides you through the fundamental concepts of matrix operations, building from basic computations to deeper understanding of linear systems and vector independence.

In [1]:
## Setup
import numpy as np
import matplotlib.pyplot as plt

def setup_plot():
    plt.figure(figsize=(10, 6))
    plt.grid(True)
    plt.axhline(y=0, color='k', linestyle=':')
    plt.axvline(x=0, color='k', linestyle=':')
    
## Vector Operations
def plot_vector(v, color='blue', label=None):
    """Plot a 2D vector from origin"""
    plt.quiver(0, 0, v[0], v[1],
              angles='xy', scale_units='xy', scale=1,
              color=color, label=label)

### Part 1: Matrix-Vector Multiplication 
A. Understanding Row vs Column Perspectives 
Consider the matrix A and vector x:
$$ 
\begin{equation} A =
\begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix} 
\end{equation}
$$
$$ 
\begin{equation} x =
\begin{bmatrix} 
2 & -1 & 1 
\end{bmatrix} 
\end{equation}
$$

##### 1. Theory: Explain in your own words: 
* How do we compute Ax by rows? 
    To compute the row matrix of Ax
$$\text 2(1) - 1(2) + 1(3) = b$$
$$\text 2(4) - 1(5) + 1(6) = b$$
$$\text 2(7) - 1(8) + 1(9) = b$$

* How do we compute Ax by columns? 
    To compute the column matrix of Ax
$$ 
\begin{equation} 2
\begin{bmatrix} 
1 \\ 
4 \\
7
\end{bmatrix} - 1
\begin{bmatrix} 
2 \\ 
5 \\
8
\end{bmatrix} + 1
\begin{bmatrix} 
3 \\ 
6 \\
9
\end{bmatrix} = b
\end{equation}
$$

* Why do both methods give the same result?

##### 2. Implementation: Complete the code to compute Ax both ways:


In [38]:
def compute_by_rows(A, x):
    """Demonstrate row-wise multiplication"""
    row_matrix = A * x
    print("The row matrix of Ax is:\n" + str(row_matrix))

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
x = np.array([[2], [-1], [1]])

compute_by_rows(A, x)
print(x)


The row matrix of Ax is:
[[ 2  4  6]
 [-4 -5 -6]
 [ 7  8  9]]
[[ 2]
 [-1]
 [ 1]]


In [39]:
def multiply_matrices(A, x):
    col_mat = x[0] * np.array([A[0][0], A[1][0], A[2][0]]) + x[1] * np.array([A[0][1], A[1][1], A[2][1]]) + x[2] * np.array([A[0][2], A[1][2], A[2][2]])
    
    print("The column matrix of Ax is:\n" + str(col_mat))
    
multiply_matrices(A, x)

The column matrix of Ax is:
[ 3  9 15]


##### 3. Analysis:
* Compare your results from both methods 
* Which method is more intuitive? Why? 
* Which method might be more efficient computationally?

### Part 2: Linear Systems 
A. An Invertible Matrix 
Study the difference matrix from lecture:
$$ 
\begin{equation} A =
\begin{bmatrix} 
2 & -1 & 0 \\ 
-1 & 2 & -1 \\
0 & -1 & 2
\end{bmatrix} 
\end{equation}
$$

##### 1. Theory: For this matrix: 
* What does each row represent?
    * System of linear equations: each row corresponds to one equation in the system.
    * Vector Representation: each row can be considered a row vector, containing a set of elements that represent coordinates in a vector space.
* Why is it called a “difference” matrix? 
    * It contains differences of the in put vector x.
* What happens when we multiply it by a vector? 
    * We get a new vector. 

##### 2. Implementation: Investigate its properties:

In [36]:
A = np.array([ [2,-1, 0], [-1, 2,-1], [0,-1, 2] ])
print("The inverse of A is:\n" + str(np.linalg.inv(A)))

The inverse of A is:
[[0.75 0.5  0.25]
 [0.5  1.   0.5 ]
 [0.25 0.5  0.75]]


##### B. Non-invertible Systems 
Now consider the matrix C from lecture:
$$ 
\begin{equation} C =
\begin{bmatrix} 
1 & -1 & 0 \\ 
-1 & 2 & -1 \\
0 & -1 & 1
\end{bmatrix} 
\end{equation}
$$
##### 1. Theory: 
* Why isn’t this matrix invertible? 
    * Because the Cx has infinite solutions to the value of x.
* What does this mean geometrically? 
    * No linear combination of these three vectors and the columns of C are in the same plane. 
##### 2. Implementation:

In [ ]:
def explore_noninvertible(C): 
    # TODO: Find a non-zero vector x where Cx = 0 
    # TODO: Try to solve Cx = b for various b 
    # pass

#### 3. Analysis:
* What patterns do you notice in the solutions?
* How does this connect to vector independence?

## Part 3: Vector Independence 
### A. Testing Independence 
Using the columns of our matrices A and C:
$$ 
\begin{equation} A =
\begin{bmatrix} 
2 & -1 & 0 \\ 
-1 & 2 & -1 \\
0 & -1 & 2
\end{bmatrix} 
\end{equation}
$$
$$ 
\begin{equation} C =
\begin{bmatrix} 
1 & -1 & 0 \\ 
-1 & 2 & -1 \\
0 & -1 & 1
\end{bmatrix} 
\end{equation}
$$

#### 1. Theory: 
* What makes vectors independent? 
* How can we test for independence?