In [1]:
## Setup
import numpy as np
import matplotlib.pyplot as plt

def setup_plot():
    plt.figure(figsize=(10, 6))
    plt.grid(True)
    plt.axhline(y=0, color='k', linestyle=':')
    plt.axvline(x=0, color='k', linestyle=':')
    
## Vector Operations
def plot_vector(v, color='blue', label=None):
    """Plot a 2D vector from origin"""
    plt.quiver(0, 0, v[0], v[1],
              angles='xy', scale_units='xy', scale=1,
              color=color, label=label)

# Vector Spaces and Matrix Operations
## Part 1: Vector Space Properties and Operations (5 points) 
1. (2 points) For vectors u = [1 2] and v = [−1 3 ], compute:

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) 2u+v and explain each step


In [6]:
def compute_vectors(u, v):
    """Demonstrate row-wise multiplication"""
    vector_comp = 2*u + v
    print("The computation of 2u+v is:\n" + str(vector_comp))

u = np.array([[1], [2]])
v = np.array([[-1], [3]])

compute_vectors(u, v)



The computation of 2u+v is:
[[1]
 [7]]


$$ 
\begin{equation} First: 2
\begin{bmatrix} 
1 \\ 
2 
\end{bmatrix} +
\begin{bmatrix} 
-1 \\ 
3
\end{bmatrix} =
\begin{bmatrix} 
2 \\ 
4
\end{bmatrix} +
\begin{bmatrix} 
-1 \\ 
3
\end{bmatrix}
\end{equation}
$$
$$ 
\begin{equation} Second:
\begin{bmatrix} 
2 \\ 
4
\end{bmatrix} +
\begin{bmatrix} 
-1 \\ 
3
\end{bmatrix} =
\begin{bmatrix} 
1 \\ 
7
\end{bmatrix}
\end{equation}
$$

## Part 2: Matrix Operations (5 points)
1. (3 points) Given matrix
$$ 
\begin{equation} First: A = 
\begin{bmatrix} 
1 & 2 \\
3 & 4
\end{bmatrix}
\end{equation}
$$
$$ 
\begin{equation} First: x = 
\begin{bmatrix} 
1 \\
-1
\end{bmatrix}
\end{equation}
$$

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) Compute 𝐴x using row method and show all steps
* By rows: First row (1 * 1 + 2 * -1) Second Row (3 * 1 + 4 * -1)
The vector for this would be:
$$ 
\begin{equation} 
\begin{bmatrix} 
1*1 + 2*-1 \\
3*1 + 4*-1
\end{bmatrix} =
\begin{bmatrix} 
-1 \\
-1
\end{bmatrix} 
\end{equation}
$$
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b) Compute 𝐴x using column method and show all steps
* The same multiplication viewed as column combinations:
$$ 
\begin{equation} Ax = 1
\begin{bmatrix} 
1 \\
3
\end{bmatrix} - 1
\begin{bmatrix} 
2 \\
4
\end{bmatrix} =
\begin{bmatrix} 
-1 \\
-1
\end{bmatrix} 
\end{equation}
$$
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c) Explain why both methods give the same result, using the definition of matrix multiplication
* They are both the same equations but written in a different manner. The column method seems to be easier to follow than the row method because it's in linear form.

In [9]:
def matrix_operation(A, x):
    """Demonstrate row-wise multiplication"""
    matrix_op = A @ x
    print("The matrix A * x is:\n" + str(matrix_op))

A = np.array([[1, 2], [3, 4]])
x = np.array([[1], [-1]])

matrix_operation(A, x)

The matrix A * x is:
[[-1]
 [-1]]


2. (2 points) For the same matrix 𝐴:

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) Find the transpose of A
* The transpose of A is found by flipping the matrix over the diagonal. In the case of A we have:
$$
\begin{equation} A^{T} =
\begin{bmatrix} 
1 & 3 \\
2 & 4
\end{bmatrix} 
\end{equation}
$$

In [10]:
A_tran = np.transpose(A)
print(A_tran)

[[1 3]
 [2 4]]


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b) Verify that (A<sup>T</sup>)<sup>T</sup> = A
* Since the transpose of A is found by flipping the matrix over the diagonal, completing another transpose of the square matrix provides the same A matrix.
\begin{equation} (A^{T})^{T} =
\begin{bmatrix} 
1 & 2 \\
3 & 4
\end{bmatrix} 
\end{equation}
$$


In [11]:
A_tran_tran = np.transpose(A_tran)
print(A_tran_tran)

[[1 2]
 [3 4]]


## Part3: LinearIndependenceandBasis(5points)
1. (3points)Determine if these vectors are linearly independent:
$$
\begin{equation} v_{1} =
\begin{bmatrix}
1 \\
0 \\
1
\end{bmatrix} , v_{2} =
\begin{bmatrix}
0 \\
1 \\
1
\end{bmatrix} , v_{3} =
\begin{bmatrix} 
1 \\
1 \\
2
\end{bmatrix}
\end{equation}
$$

* The vector v_{1} and v_{2} can be added to make v_{3}. This shows that v_{3} is dependent. 

$$
\begin{bmatrix}
1 \\
0 \\
1
\end{bmatrix} +
\begin{bmatrix}
0 \\
1 \\
1
\end{bmatrix} =
\begin{bmatrix}
1 \\
1 \\
2
\end{bmatrix}
$$

2. (2points)For the standard basis vectors in R<sup>2</sup>:

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a)Write them explicitly
$$
\begin{equation} e_{1} =
\begin{bmatrix} 
1 \\
0 
\end{bmatrix} , e_{2} =
\begin{bmatrix} 
0 \\
1
\end{bmatrix}
\end{equation}
$$

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b) Explain why they form a basis
* They are lineraly independent and span the space of R<sup>2</sup>

## Part 4: The Four Fundamental Subspaces (5 points)
1. (3 points) For the matrix
$$
\begin{equation} A =
\begin{bmatrix}
1 && 2 && 3 \\
2 && 4 && 6
\end{bmatrix}
\end{equation}
$$

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) Find a basis for the column space using the systematic method from class
* Row 2 is a multiple of row 1. The row space should be:
$$
\begin{bmatrix}
1 \\
1 \\
0
\end{bmatrix}
$$

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b) Find a basis for the nullspace using the row reduction method
$$
\begin{equation} -R1*2
\begin{bmatrix}
1 && 2 && 3 \\
2 && 4 && 6
\end{bmatrix} = 
\begin{bmatrix}
1 && 2 && 3 \\
0 && 0 && 0
\end{bmatrix}
\end{equation}
$$

* The nullspace should be: 
$$
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$


2. (2 points) For this matrix:

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) Is the system 𝐴𝑥 = 𝑏 underdetermined or overdetermined? Why?
* Underdetermined Systems (p > n). There are two equation and five unknowns.
$$
\begin{equation} A =
\begin{bmatrix}
1 && 2 && 3 \\
2 && 4 && 6
\end{bmatrix} , x = 
\begin{bmatrix} 
x_{1} \\
x_{2} \\
x_{3}
\end{bmatrix}
\begin{bmatrix} 
b_{1} \\
b_{2} 
\end{bmatrix}
\end{equation}
$$


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b) What does this mean for solutions to 𝐴𝑥 = 𝑏?
* This means that multiple solutions typically exist and there is a freedom of solution space.

## Part 5: Vector Decomposition (5 points)
1. (3 points) Given
$$
\begin{equation} A =
\begin{bmatrix}
1 && -1 \\
-1 && 1
\end{bmatrix}
\end{equation}
$$

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) Find a vector in the row space
* The row space of A is r = [1 -1].

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b) Find a vector in the nullspace

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c) Show these vectors are orthogonal
* The nullspace is:
$$
\begin{equation} x =
\begin{bmatrix}
1 \\
1
\end{bmatrix}
\end{equation}
$$

To verify this r * x = 1 * 1 + 1 * -1 = 0


2. (2 points) For a vector 𝑥 in the domain of 𝐴:

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) What does it mean to decompose 𝑥 into row space and nullspace components?
* Row space shows which linear combinations of coordinates are possible Nullspace 𝑁 (𝐴) = all solutions to 𝐴𝑥 = 0
* Nullspace 𝑁 (𝐴) = all solutions to 𝐴𝑥 = 0
    * In other words, the nullspace is a vector that multiplied with the row space, the product is zero.

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b) Why must these components be orthogonal?
* To ensure that the two vectors are zero.

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c How does this relate to the Fundamental Orthogonality Theorem?
* Any vector 𝑥 uniquely decomposes as 𝑥 = 𝑥<sub>𝑟</sub> + 𝑥<sub>𝑛</sub> where:
    * 𝑥<sub>𝑟</sub> is in row space Row(𝐴)
    * 𝑥<sub>𝑛</sub> is in nullspace 𝑁 (𝐴)
    * 𝑥<sub>𝑟</sub> ⟂ 𝑥<sub>𝑛</sub> (orthogonal components)