In [1]:
## Setup
import numpy as np
import matplotlib.pyplot as plt

def setup_plot():
    plt.figure(figsize=(10, 6))
    plt.grid(True)
    plt.axhline(y=0, color='k', linestyle=':')
    plt.axvline(x=0, color='k', linestyle=':')
    
## Vector Operations
def plot_vector(v, color='blue', label=None):
    """Plot a 2D vector from origin"""
    plt.quiver(0, 0, v[0], v[1],
              angles='xy', scale_units='xy', scale=1,
              color=color, label=label)

# Vector Spaces and Matrix Operations
## Part 1: Vector Space Properties and Operations (5 points) 
1. (2 points) For vectors u = [1 2] and v = [−1 3 ], compute:

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) 2u+v and explain each step


In [6]:
def compute_vectors(u, v):
    """Demonstrate row-wise multiplication"""
    vector_comp = 2*u + v
    print("The computation of 2u+v is:\n" + str(vector_comp))

u = np.array([[1], [2]])
v = np.array([[-1], [3]])

compute_vectors(u, v)



The computation of 2u+v is:
[[1]
 [7]]


$$ 
\begin{equation} First: 2
\begin{bmatrix} 
1 \\ 
2 
\end{bmatrix} +
\begin{bmatrix} 
-1 \\ 
3
\end{bmatrix} =
\begin{bmatrix} 
2 \\ 
4
\end{bmatrix} +
\begin{bmatrix} 
-1 \\ 
3
\end{bmatrix}
\end{equation}
$$
$$ 
\begin{equation} Second:
\begin{bmatrix} 
2 \\ 
4
\end{bmatrix} +
\begin{bmatrix} 
-1 \\ 
3
\end{bmatrix} =
\begin{bmatrix} 
1 \\ 
7
\end{bmatrix}
\end{equation}
$$

## Part 2: Matrix Operations (5 points)
1. (3 points) Given matrix
$$ 
\begin{equation} First: A = 
\begin{bmatrix} 
1 & 2 \\
3 & 4
\end{bmatrix}
\end{equation}
$$
$$ 
\begin{equation} First: x = 
\begin{bmatrix} 
1 \\
-1
\end{bmatrix}
\end{equation}
$$

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) Compute 𝐴x using row method and show all steps
* By rows: First row (1 * 1 + 2 * -1) Second Row (3 * 1 + 4 * -1)
The vector for this would be:
$$ 
\begin{equation} 
\begin{bmatrix} 
1*1 + 2*-1 \\
3*1 + 4*-1
\end{bmatrix} =
\begin{bmatrix} 
-1 \\
-1
\end{bmatrix} 
\end{equation}
$$
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b) Compute 𝐴x using column method and show all steps
* The same multiplication viewed as column combinations:
$$ 
\begin{equation} Ax = 1
\begin{bmatrix} 
1 \\
3
\end{bmatrix} - 1
\begin{bmatrix} 
2 \\
4
\end{bmatrix} =
\begin{bmatrix} 
-1 \\
-1
\end{bmatrix} 
\end{equation}
$$
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c) Explain why both methods give the same result, using the definition of matrix multiplication
* They are both the same equations but written in a different manner. The column method seems to be easier to follow than the row method because it's in linear form.

In [9]:
def matrix_operation(A, x):
    """Demonstrate row-wise multiplication"""
    matrix_op = A @ x
    print("The matrix A * x is:\n" + str(matrix_op))

A = np.array([[1, 2], [3, 4]])
x = np.array([[1], [-1]])

matrix_operation(A, x)

The matrix A * x is:
[[-1]
 [-1]]


2. (2 points) For the same matrix 𝐴:

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a) Find the transpose of A
* The transpose of A is found by flipping the matrix over the diagonal. In the case of A we have:
$$
\begin{equation} A^{T} =
\begin{bmatrix} 
1 & 3 \\
2 & 4
\end{bmatrix} 
\end{equation}
$$

In [10]:
A_tran = np.transpose(A)
print(A_tran)

[[1 3]
 [2 4]]


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b) Verify that (A<sup>T</sup>)<sup>T</sup> = A
* Since the transpose of A is found by flipping the matrix over the diagonal, completing another transpose of the square matrix provides the same A matrix.
\begin{equation} (A^{T})^{T} =
\begin{bmatrix} 
1 & 2 \\
3 & 4
\end{bmatrix} 
\end{equation}
$$


In [11]:
A_tran_tran = np.transpose(A_tran)
print(A_tran_tran)

[[1 2]
 [3 4]]


## Part3: LinearIndependenceandBasis(5points)
1. (3points)Determine if these vectors are linearly independent:
$$
\begin{equation} v_{1} =
\begin{bmatrix}
1 \\
0 \\
1
\end{bmatrix} , v_{2} =
\begin{bmatrix}
0 \\
1 \\
1
\end{bmatrix} , v_{3} =
\begin{bmatrix} 
1 \\
1 \\
2
\end{bmatrix}
\end{equation}
$$
